# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    command: [ "curl -sSL https://github.com/arevindh/pihole-speedtest/raw/master/test | sudo bash -s -- -o ~/speedtest.db" ]
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "4443:443/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'peatonet'
    # Volumes store your data between container upgrades
    volumes:
      - '/mnt/sd/pihole/etc-pihole/:/etc/pihole/'
      - '/mnt/sd/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - '/mnt/sd/pihole/backups:/backups'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
